version: "3.8"

services:
  auth:
    build:
      target: development
    volumes:
      - ./auth:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: yarn start:dev

  gateway:
    build:
      target: development
    volumes:
      - ./gateway:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: yarn start:dev
