version: "3.8"

services:
  database:
    container_name: database_container_prod

  auth:
    build:
      target: development
    container_name: auth_container_dev
    volumes:
      - ./auth:/usr/src/app:cached
      - auth_app:/usr/src/app/node_modules
    command: yarn start:dev

  gateway:
    build:
      target: development
    container_name: gateway_container_dev
    volumes:
      - ./gateway:/usr/src/app:cached
      - gateway_app:/usr/src/app/node_modules
    command: yarn start:dev

volumes:
  auth_app:
  gateway_app: