version: "3.8"

services:
  database:
    image: postgres:latest
    restart: always
    hostname: database
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: ./var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices_backend
    env_file:
      - .env

  auth:
    build:
      context: ./auth
      dockerfile: ./docker/Dockerfile
    restart: always
    hostname: token
    networks:
      - microservices_backend
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}

  gateway:
    build:
      context: ./gateway
      dockerfile: ./docker/Dockerfile
    restart: always
    hostname: gateway
    networks:
      - microservices_backend
    env_file:
      - .env
    depends_on:
      - postgres
      - auth
    links:
      - postgres
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}

networks:
  microservices_backend:
    driver: bridge

volumes:
  pgdata:
